// lib/constructs/http-api.ts

// Replaces ALB + ECS Fargate (Go) - ~90% cost reduction

import * as path from "path";
import { Construct } from "constructs";
import * as lambda from "aws-cdk-lib/aws-lambda";
import * as lambdaNode from "aws-cdk-lib/aws-lambda-nodejs";
import * as apigatewayv2 from "aws-cdk-lib/aws-apigatewayv2";
import * as integrations from "aws-cdk-lib/aws-apigatewayv2-integrations";
import * as sqs from "aws-cdk-lib/aws-sqs";
import * as dynamodb from "aws-cdk-lib/aws-dynamodb";
import * as logs from "aws-cdk-lib/aws-logs";
import * as cloudwatch from "aws-cdk-lib/aws-cloudwatch";
import * as sns from "aws-cdk-lib/aws-sns";
import * as actions from "aws-cdk-lib/aws-cloudwatch-actions";
import * as iam from "aws-cdk-lib/aws-iam";
import * as cdk from "aws-cdk-lib";
import { Duration, RemovalPolicy, SecretValue } from "aws-cdk-lib";
import { StageConfig } from "../config/stage-config";
import { createBaseLambdaConfig, createPowertoolsEnv } from "./lambda-config";

interface HttpApiConstructProps {
  stackName: string;
  stage: string;
  matchingQueue: sqs.IQueue;
  sessionCacheTable: dynamodb.ITable;
  /** AR-XXX: Full payload table for gRPC stub */
  sessionPayloadTable: dynamodb.ITable;
  /** Optional: Vector results table for async vector search results */
  vectorResultsTable?: dynamodb.ITable;
  /** Integrity results table for VM integrity check storage */
  integrityResultsTable: dynamodb.ITable;
  alarmsTopic: sns.ITopic;
  /** Stage-specific configuration for Lambda memory tuning */
  config: StageConfig;
  /** Optional: probe tokens table name (for sigint token redemption) */
  probeTokensTableName?: string;
  /** Optional: probe tokens table ARN (for IAM grant) */
  probeTokensTableArn?: string;
  /** Optional: SIGINT AES key secret ARN (for sigint token HMAC verification) */
  sigintAesKeySecretArn?: string;
  /**
   * Optional: SSM SecureString parameter name holding the ECDH key pair
   * for encrypted payload ingestion from ms-argus-web.
   * Generated by: npx tsx scripts/generate-ecdh-key.ts
   * Format: /${stackName}/ecdh-keypair
   */
  ecdhKeyParamName?: string;
  /** Optional: Signal baselines table for population-based signal learning */
  signalBaselinesTable?: dynamodb.ITable;
}

/**
 * HTTP API Gateway + Lambda for fingerprint ingestion
 *
 * Why HTTP API instead of REST API:
 * - $1/million vs $3.50/million requests (70% cheaper)
 * - Lower latency (no additional validation overhead)
 * - Native Lambda integration
 *
 * Why Lambda instead of Go/ECS:
 * - Zero idle cost (pay per invocation)
 * - No ALB (~$16/month), no Fargate (~$10-25/month)
 * - Simpler infrastructure (no VPC for ingestion)
 * - TypeScript consistency with rest of codebase
 */
export class HttpApiConstruct extends Construct {
  public readonly api: apigatewayv2.HttpApi;
  public readonly ingestionFunction: lambda.Function;
  public readonly sessionGetFunction: lambda.Function;
  public readonly apiEndpoint: string;

  constructor(scope: Construct, id: string, props: HttpApiConstructProps) {
    super(scope, id);

    const {
      stackName,
      stage,
      matchingQueue,
      sessionCacheTable,
      sessionPayloadTable,
      vectorResultsTable,
      integrityResultsTable,
      probeTokensTableName,
      sigintAesKeySecretArn,
      alarmsTopic,
      config,
      ecdhKeyParamName,
    } = props;

    // CloudWatch log group for Lambda
    const logGroup = new logs.LogGroup(this, "IngestionLogGroup", {
      logGroupName: `/aws/lambda/${stackName}-ingestion`,
      retention: logs.RetentionDays.ONE_MONTH,
      removalPolicy: RemovalPolicy.DESTROY,
    });

    // Lambda function for ingestion

    this.ingestionFunction = new lambdaNode.NodejsFunction(
      this,
      "IngestionFunction",
      {
        ...createBaseLambdaConfig(),
        functionName: `${stackName}-ingestion`,
        handler: "handler",
        entry: path.join(__dirname, "../../src/handlers/ingestion.ts"),

        memorySize: config.lambda.ingestion.memorySize,
        timeout: Duration.seconds(10),
        logGroup,
        environment: {
          ...createPowertoolsEnv("argus-ingestion", `argus-${stage}`),
          SQS_QUEUE_URL: matchingQueue.queueUrl,
          ...(ecdhKeyParamName && { ECDH_KEY_PARAM: ecdhKeyParamName }),
          INTEGRITY_RESULTS_TABLE: integrityResultsTable.tableName,
          ...(process.env.INTEGRITY_DEPLOY_SECRET && {
            INTEGRITY_DEPLOY_SECRET: process.env.INTEGRITY_DEPLOY_SECRET,
          }),
          ...(sigintAesKeySecretArn && {
            SIGINT_AES_KEY: SecretValue.secretsManager(
              sigintAesKeySecretArn,
            ).unsafeUnwrap(),
          }),
          ...(probeTokensTableName && {
            PROBE_TOKENS_TABLE_NAME: probeTokensTableName,
          }),
          ...(props.signalBaselinesTable && {
            SIGNAL_BASELINES_TABLE: props.signalBaselinesTable.tableName,
          }),
        },
      },
    );

    // Grant SQS permissions
    matchingQueue.grantSendMessages(this.ingestionFunction);

    this.grantIngestionPermissions(props);

    const sessionGetLogGroup = new logs.LogGroup(this, "SessionGetLogGroup", {
      logGroupName: `/aws/lambda/${stackName}-session-get`,
      retention: logs.RetentionDays.ONE_MONTH,
      removalPolicy: RemovalPolicy.DESTROY,
    });

    this.sessionGetFunction = new lambdaNode.NodejsFunction(
      this,
      "SessionGetFunction",
      {
        ...createBaseLambdaConfig(),
        functionName: `${stackName}-session-get`,
        handler: "handler",
        entry: path.join(__dirname, "../../src/handlers/session-get.ts"),

        memorySize: config.lambda.sessionGet.memorySize,
        timeout: Duration.seconds(10),
        logGroup: sessionGetLogGroup,
        environment: {
          ...createPowertoolsEnv("argus-session-get", `argus-${stage}`),
          SESSION_CACHE_TABLE: sessionCacheTable.tableName,
          // AR-XXX: Full payload table for gRPC stub
          SESSION_PAYLOAD_TABLE: sessionPayloadTable.tableName,
          // Vector results table for async vector search results
          ...(vectorResultsTable && {
            VECTOR_RESULTS_TABLE: vectorResultsTable.tableName,
          }),
          INTEGRITY_RESULTS_TABLE: integrityResultsTable.tableName,
          STACK_NAME: stackName,
        },
      },
    );

    // Grant DynamoDB read permissions
    sessionCacheTable.grantReadData(this.sessionGetFunction);
    sessionPayloadTable.grantReadData(this.sessionGetFunction);
    integrityResultsTable.grantReadData(this.sessionGetFunction);

    // Grant SSM read for integrity API key validation
    this.sessionGetFunction.addToRolePolicy(
      new iam.PolicyStatement({
        actions: ["ssm:GetParameter"],
        resources: [
          `arn:aws:ssm:${cdk.Stack.of(this).region}:${cdk.Stack.of(this).account}:parameter/${stackName}/integrity-api-key`,
        ],
      }),
    );
    if (vectorResultsTable) {
      vectorResultsTable.grantReadData(this.sessionGetFunction);
    }

    // HTTP API Gateway — CORS is intentionally handled at the Lambda layer
    // (see helpers/cors-middleware.ts). API GW's `corsPreflight` only accepts
    // a static origin list, which breaks `credentials: 'include'` flows that
    // need per-request origin reflection + `Access-Control-Allow-Credentials`.
    // Removing it here routes OPTIONS preflight to the Lambda, where the
    // middleware reflects Origin and emits ACAC:true correctly.
    this.api = new apigatewayv2.HttpApi(this, "HttpApi", {
      apiName: `${stackName}-api`,
      description: "Argus fingerprint ingestion API",
    });

    // Lambda integration
    const lambdaIntegration = new integrations.HttpLambdaIntegration(
      "IngestionIntegration",
      this.ingestionFunction,
    );

    // Routes. OPTIONS is added to every non-health path so preflight hits
    // the Lambda (which emits CORS + ACAC:true via cors-middleware). We had
    // gateway-level corsPreflight handling this before, but that only supports
    // static `allowOrigins` lists — incompatible with `credentials: 'include'`
    // which needs per-request Origin reflection.
    this.api.addRoutes({
      path: "/v1/collect",
      methods: [apigatewayv2.HttpMethod.POST, apigatewayv2.HttpMethod.OPTIONS],
      integration: lambdaIntegration,
    });

    this.api.addRoutes({
      path: "/health",
      methods: [apigatewayv2.HttpMethod.GET],
      integration: lambdaIntegration,
    });

    this.api.addRoutes({
      path: "/v1/handshake",
      methods: [apigatewayv2.HttpMethod.GET, apigatewayv2.HttpMethod.OPTIONS],
      integration: lambdaIntegration,
    });

    this.api.addRoutes({
      path: "/v1/integrity-collect",
      methods: [apigatewayv2.HttpMethod.POST, apigatewayv2.HttpMethod.OPTIONS],
      integration: lambdaIntegration,
    });

    const sessionGetIntegration = new integrations.HttpLambdaIntegration(
      "SessionGetIntegration",
      this.sessionGetFunction,
    );

    this.api.addRoutes({
      path: "/v1/integrity-session/{session_id}",
      methods: [apigatewayv2.HttpMethod.GET, apigatewayv2.HttpMethod.OPTIONS],
      integration: sessionGetIntegration,
    });

    this.api.addRoutes({
      path: "/v1/session/{session_id}",
      methods: [apigatewayv2.HttpMethod.GET, apigatewayv2.HttpMethod.OPTIONS],
      integration: sessionGetIntegration,
    });

    // Store endpoint URL (without trailing slash)
    this.apiEndpoint = this.api.apiEndpoint;

    // Alarms
    if (config.alarms.enabled) {
      this.createAlarms(stackName, alarmsTopic);
    }
  }

  private grantIngestionPermissions(props: HttpApiConstructProps): void {
    const {
      integrityResultsTable,
      probeTokensTableArn,
      sigintAesKeySecretArn,
      ecdhKeyParamName,
    } = props;

    integrityResultsTable.grantWriteData(this.ingestionFunction);

    if (props.signalBaselinesTable) {
      props.signalBaselinesTable.grantReadWriteData(this.ingestionFunction);
    }

    if (probeTokensTableArn) {
      this.ingestionFunction.addToRolePolicy(
        new iam.PolicyStatement({
          actions: ["dynamodb:GetItem"],
          resources: [probeTokensTableArn],
        }),
      );
    }

    if (sigintAesKeySecretArn) {
      this.ingestionFunction.addToRolePolicy(
        new iam.PolicyStatement({
          actions: ["secretsmanager:GetSecretValue"],
          resources: [sigintAesKeySecretArn],
        }),
      );
    }

    if (ecdhKeyParamName) {
      this.ingestionFunction.addToRolePolicy(
        new iam.PolicyStatement({
          actions: ["ssm:GetParameter"],
          resources: [
            `arn:aws:ssm:${cdk.Stack.of(this).region}:${cdk.Stack.of(this).account}:parameter${ecdhKeyParamName}`,
          ],
        }),
      );
    }
  }

  private createAlarms(stackName: string, alarmsTopic: sns.ITopic): void {
    // Lambda errors alarm
    const errorsAlarm = new cloudwatch.Alarm(this, "IngestionErrorsAlarm", {
      metric: this.ingestionFunction.metricErrors({
        period: Duration.minutes(5),
        statistic: "Sum",
      }),
      threshold: 10,
      evaluationPeriods: 2,
      alarmDescription: `${stackName} ingestion Lambda errors > 10 in 5 min`,
    });
    errorsAlarm.addAlarmAction(new actions.SnsAction(alarmsTopic));

    // Lambda duration alarm (p99)
    const durationAlarm = new cloudwatch.Alarm(this, "IngestionDurationAlarm", {
      metric: this.ingestionFunction.metricDuration({
        period: Duration.minutes(5),
        statistic: "p99",
      }),
      threshold: 5000, // 5 seconds
      evaluationPeriods: 3,
      alarmDescription: `${stackName} ingestion Lambda p99 duration > 5s`,
    });
    durationAlarm.addAlarmAction(new actions.SnsAction(alarmsTopic));

    // Lambda throttles alarm
    const throttlesAlarm = new cloudwatch.Alarm(
      this,
      "IngestionThrottlesAlarm",
      {
        metric: this.ingestionFunction.metricThrottles({
          period: Duration.minutes(5),
          statistic: "Sum",
        }),
        threshold: 5,
        evaluationPeriods: 2,
        alarmDescription: `${stackName} ingestion Lambda throttled > 5 times`,
      },
    );
    throttlesAlarm.addAlarmAction(new actions.SnsAction(alarmsTopic));
  }
}
