// lib/constructs/http-api.ts

import * as path from "path";
import { Construct } from "constructs";
import * as lambda from "aws-cdk-lib/aws-lambda";
import * as lambdaNode from "aws-cdk-lib/aws-lambda-nodejs";
import * as apigatewayv2 from "aws-cdk-lib/aws-apigatewayv2";
import * as integrations from "aws-cdk-lib/aws-apigatewayv2-integrations";
import * as dynamodb from "aws-cdk-lib/aws-dynamodb";
import * as logs from "aws-cdk-lib/aws-logs";
import * as cloudwatch from "aws-cdk-lib/aws-cloudwatch";
import * as sns from "aws-cdk-lib/aws-sns";
import * as actions from "aws-cdk-lib/aws-cloudwatch-actions";
import * as iam from "aws-cdk-lib/aws-iam";
import * as cdk from "aws-cdk-lib";
import { Duration, RemovalPolicy, SecretValue } from "aws-cdk-lib";
import { StageConfig } from "../config/stage-config";
import { createBaseLambdaConfig, createPowertoolsEnv } from "./lambda-config";

interface HttpApiConstructProps {
  stackName: string;
  stage: string;
  /** Integrity results table for integrity-collect storage + session-get reads. */
  integrityResultsTable: dynamodb.ITable;
  alarmsTopic: sns.ITopic;
  /** Stage-specific configuration for Lambda memory tuning */
  config: StageConfig;
  /** Optional: probe tokens table name (for sigint token redemption) */
  probeTokensTableName?: string;
  /** Optional: probe tokens table ARN (for IAM grant) */
  probeTokensTableArn?: string;
  /** Optional: SIGINT AES key secret ARN (for sigint token HMAC verification) */
  sigintAesKeySecretArn?: string;
  /**
   * Optional: SSM SecureString parameter name holding the ECDH key pair
   * for encrypted payload ingestion from ms-argus-web-integrity.
   * Generated by: npx tsx scripts/generate-ecdh-key.ts
   * Format: /${stackName}/ecdh-keypair
   */
  ecdhKeyParamName?: string;
  /**
   * Optional: Firehose delivery stream name for batched NDJSON archive.
   * When set, the ingestion handler dual-writes to DDB and Firehose.
   */
  integrityFirehoseStreamName?: string;
  /**
   * SSM path of the ms-argus-platform Ed25519 public key used to verify
   * merchant API tokens. Format: `/argus-platform/{env}/api-signing-pubkey`.
   */
  platformPubkeySsmPath: string;
  /**
   * Name of the platform's merchants Dynamo table — passed to the session-get
   * Lambda as MERCHANTS_TABLE_NAME so it can atomically decrement credits per
   * billable read.
   */
  merchantsTableName: string;
  /**
   * ARN of the platform's merchants Dynamo table. Used to scope the IAM
   * `dynamodb:UpdateItem` grant on session-get.
   */
  merchantsTableArn: string;
}

/**
 * HTTP API Gateway + Lambda for the integrity collection surface:
 *
 *   POST /v1/integrity-collect → ingestion Lambda
 *   GET  /health               → ingestion Lambda (static)
 *
 * The session-get Lambda is fronted only by the merchant REST API (see
 * RestApiConstruct); it's referenced from this construct purely so the
 * stack can grant table reads + SSM access in one place.
 *
 * OPTIONS preflight routes to the ingestion Lambda so the cors-middleware
 * can reflect Origin and emit `Access-Control-Allow-Credentials: true`
 * (required for the `_fpid` cross-subdomain cookie flow).
 */
export class HttpApiConstruct extends Construct {
  public readonly api: apigatewayv2.HttpApi;
  public readonly ingestionFunction: lambda.Function;
  public readonly sessionGetFunction: lambda.Function;
  public readonly apiEndpoint: string;

  constructor(scope: Construct, id: string, props: HttpApiConstructProps) {
    super(scope, id);

    const {
      stackName,
      stage,
      integrityResultsTable,
      probeTokensTableName,
      sigintAesKeySecretArn,
      alarmsTopic,
      config,
      ecdhKeyParamName,
      integrityFirehoseStreamName,
      platformPubkeySsmPath,
      merchantsTableName,
      merchantsTableArn,
    } = props;

    const logGroup = new logs.LogGroup(this, "IngestionLogGroup", {
      logGroupName: `/aws/lambda/${stackName}-ingestion`,
      retention: logs.RetentionDays.ONE_MONTH,
      removalPolicy: RemovalPolicy.DESTROY,
    });

    this.ingestionFunction = new lambdaNode.NodejsFunction(
      this,
      "IngestionFunction",
      {
        ...createBaseLambdaConfig(),
        functionName: `${stackName}-ingestion`,
        handler: "handler",
        entry: path.join(__dirname, "../../src/handlers/ingestion.ts"),
        memorySize: config.lambda.ingestion.memorySize,
        timeout: Duration.seconds(10),
        logGroup,
        environment: {
          ...createPowertoolsEnv("argus-ingestion", `argus-${stage}`, stage),
          ...(ecdhKeyParamName && { ECDH_KEY_PARAM: ecdhKeyParamName }),
          INTEGRITY_RESULTS_TABLE: integrityResultsTable.tableName,
          ...(process.env.INTEGRITY_DEPLOY_SECRET && {
            INTEGRITY_DEPLOY_SECRET: process.env.INTEGRITY_DEPLOY_SECRET,
          }),
          ...(sigintAesKeySecretArn && {
            SIGINT_AES_KEY: SecretValue.secretsManager(
              sigintAesKeySecretArn,
            ).unsafeUnwrap(),
          }),
          ...(probeTokensTableName && {
            PROBE_TOKENS_TABLE_NAME: probeTokensTableName,
          }),
          ...(integrityFirehoseStreamName && {
            INTEGRITY_FIREHOSE_STREAM: integrityFirehoseStreamName,
          }),
        },
      },
    );

    this.grantIngestionPermissions(props);

    const sessionGetLogGroup = new logs.LogGroup(this, "SessionGetLogGroup", {
      logGroupName: `/aws/lambda/${stackName}-session-get`,
      retention: logs.RetentionDays.ONE_MONTH,
      removalPolicy: RemovalPolicy.DESTROY,
    });

    this.sessionGetFunction = new lambdaNode.NodejsFunction(
      this,
      "SessionGetFunction",
      {
        ...createBaseLambdaConfig(),
        functionName: `${stackName}-session-get`,
        handler: "handler",
        entry: path.join(__dirname, "../../src/handlers/session-get.ts"),
        memorySize: config.lambda.sessionGet.memorySize,
        timeout: Duration.seconds(10),
        logGroup: sessionGetLogGroup,
        environment: {
          ...createPowertoolsEnv("argus-session-get", `argus-${stage}`, stage),
          INTEGRITY_RESULTS_TABLE: integrityResultsTable.tableName,
          STACK_NAME: stackName,
          PLATFORM_PUBKEY_SSM_PATH: platformPubkeySsmPath,
          MERCHANTS_TABLE_NAME: merchantsTableName,
        },
      },
    );

    integrityResultsTable.grantReadData(this.sessionGetFunction);

    // SSM read for the platform's Ed25519 pubkey used to verify tokens.
    this.sessionGetFunction.addToRolePolicy(
      new iam.PolicyStatement({
        actions: ["ssm:GetParameter"],
        resources: [
          `arn:aws:ssm:${cdk.Stack.of(this).region}:${cdk.Stack.of(this).account}:parameter${platformPubkeySsmPath}`,
        ],
      }),
    );

    // Atomic credit decrement on the platform's merchants table — billing
    // happens here, on each successful session-get. Conditional UpdateItem
    // with `credits >= :one` returns 402 from the handler when it fails.
    this.sessionGetFunction.addToRolePolicy(
      new iam.PolicyStatement({
        actions: ["dynamodb:UpdateItem"],
        resources: [merchantsTableArn],
      }),
    );

    // HTTP API Gateway — CORS is handled at the Lambda layer (see
    // helpers/cors-middleware.ts) because `credentials: 'include'` requires
    // per-request Origin reflection, which API GW's static corsPreflight
    // can't do.
    this.api = new apigatewayv2.HttpApi(this, "HttpApi", {
      apiName: `${stackName}-api`,
      description: "Argus integrity collection API",
    });

    const ingestionIntegration = new integrations.HttpLambdaIntegration(
      "IngestionIntegration",
      this.ingestionFunction,
    );

    this.api.addRoutes({
      path: "/health",
      methods: [apigatewayv2.HttpMethod.GET],
      integration: ingestionIntegration,
    });

    this.api.addRoutes({
      path: "/v1/integrity-collect",
      methods: [apigatewayv2.HttpMethod.POST, apigatewayv2.HttpMethod.OPTIONS],
      integration: ingestionIntegration,
    });

    this.apiEndpoint = this.api.apiEndpoint;

    if (config.alarms.enabled) {
      this.createAlarms(stackName, alarmsTopic);
    }
  }

  private grantIngestionPermissions(props: HttpApiConstructProps): void {
    const {
      integrityResultsTable,
      probeTokensTableArn,
      sigintAesKeySecretArn,
      ecdhKeyParamName,
    } = props;

    integrityResultsTable.grantWriteData(this.ingestionFunction);

    if (probeTokensTableArn) {
      this.ingestionFunction.addToRolePolicy(
        new iam.PolicyStatement({
          actions: ["dynamodb:GetItem"],
          resources: [probeTokensTableArn],
        }),
      );
    }

    if (sigintAesKeySecretArn) {
      this.ingestionFunction.addToRolePolicy(
        new iam.PolicyStatement({
          actions: ["secretsmanager:GetSecretValue"],
          resources: [sigintAesKeySecretArn],
        }),
      );
    }

    if (ecdhKeyParamName) {
      this.ingestionFunction.addToRolePolicy(
        new iam.PolicyStatement({
          actions: ["ssm:GetParameter"],
          resources: [
            `arn:aws:ssm:${cdk.Stack.of(this).region}:${cdk.Stack.of(this).account}:parameter${ecdhKeyParamName}`,
          ],
        }),
      );
    }
  }

  private createAlarms(stackName: string, alarmsTopic: sns.ITopic): void {
    const errorsAlarm = new cloudwatch.Alarm(this, "IngestionErrorsAlarm", {
      metric: this.ingestionFunction.metricErrors({
        period: Duration.minutes(5),
        statistic: "Sum",
      }),
      threshold: 10,
      evaluationPeriods: 2,
      alarmDescription: `${stackName} ingestion Lambda errors > 10 in 5 min`,
    });
    errorsAlarm.addAlarmAction(new actions.SnsAction(alarmsTopic));

    const durationAlarm = new cloudwatch.Alarm(this, "IngestionDurationAlarm", {
      metric: this.ingestionFunction.metricDuration({
        period: Duration.minutes(5),
        statistic: "p99",
      }),
      threshold: 5000,
      evaluationPeriods: 3,
      alarmDescription: `${stackName} ingestion Lambda p99 duration > 5s`,
    });
    durationAlarm.addAlarmAction(new actions.SnsAction(alarmsTopic));

    const throttlesAlarm = new cloudwatch.Alarm(
      this,
      "IngestionThrottlesAlarm",
      {
        metric: this.ingestionFunction.metricThrottles({
          period: Duration.minutes(5),
          statistic: "Sum",
        }),
        threshold: 5,
        evaluationPeriods: 2,
        alarmDescription: `${stackName} ingestion Lambda throttled > 5 times`,
      },
    );
    throttlesAlarm.addAlarmAction(new actions.SnsAction(alarmsTopic));
  }
}
